# Generated by Django 3.2.8 on 2022-01-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginSystem',
        ),
    ]
